### ISSUE TITLE
Missing so many older Quickstarts and no way to re DL them

### ISSUE THREAD

**Issue by Elowan** [QuadSpinner/Gaea-Quickstarts#4]
hello guys,

I am looking for older quickstarts, such as "Foreground Rocks", "Mars" and so many more.
Especially those "Foreground rocks" I miss badly. On the DL page, 1.2.1.8 is the oldest, still working DL for me.

But in 1.2.1.8 the mentioned quickstarts are missing as well as with the latest 1.3.x release.

Is there a chance, to bring them back or put them up here at git?

cheers

**Comment by daxpandhi** [comment]
Hi

Some of the quickstarts would not longer work because they were made with much older version of Gaea, so they were retired. Some of the old ones are in this branch: https://github.com/QuadSpinner/Gaea-Quickstarts/tree/old/Examples

Much older files that don't load well or break upon loading were forced to be retired unfortunately.

If you post screenshots of old files, we can try and make new quickstarts with updated nodes and methodology.

**Comment by Elowan** [comment]
Hi Dax,

first of all, thank you so much for answering and congratz on the 1.3 release - I am using it for a bunch of hours and experienced no crashes or strange behaviors whatsoever :) Great piece of software, I can only imagine, what 2.0 will bring to us.

Unfortunatly, I have not found screenshots of the older stuff on my workstation. This is, why I was trying to download to older 1.2 and earlier versions, but it seems that most of the links to the old versions won´t work (at least for me).

The "foreground rocks" quickstart was looking like you would take some quixel rock assets and make a heightmap of them.
This was really awesome stuff, very very useful for creating rocks and smaller formations to use as meshes on the actual heightmap for example.

Anyways - I will check-out the examples from the link you posted, maybe I can find the one I am after.

Best
